// flow-typed signature: 11ea0bd5ff5c64ccca730c3ce95f2803
// flow-typed version: <<STUB>>/arcade_v0.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'arcade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'arcade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'arcade/index' {
  declare module.exports: $Exports<'arcade'>;
}
declare module 'arcade/index.js' {
  declare module.exports: $Exports<'arcade'>;
}
