// flow-typed signature: 5474169389595af28ed018181c840d3d
// flow-typed version: <<STUB>>/ninja_v^3.0.8/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ninja'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ninja' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ninja/build/arc' {
  declare module.exports: any;
}

declare module 'ninja/build/bin' {
  declare module.exports: any;
}

declare module 'ninja/build/graphics/pause' {
  declare module.exports: any;
}

declare module 'ninja/build/graphics/play' {
  declare module.exports: any;
}

declare module 'ninja/build/graphics/stop' {
  declare module.exports: any;
}

declare module 'ninja/build/icon' {
  declare module.exports: any;
}

declare module 'ninja/build/icons/icon' {
  declare module.exports: any;
}

declare module 'ninja/build/icons/pause' {
  declare module.exports: any;
}

declare module 'ninja/build/icons/play' {
  declare module.exports: any;
}

declare module 'ninja/build/icons/repeat' {
  declare module.exports: any;
}

declare module 'ninja/build/icons/stop' {
  declare module.exports: any;
}

declare module 'ninja/build/index' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/actions' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/components/arc/download' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/components/arc/index' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/components/arc/playback' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/components/arc/rainbow' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/components/icon' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/components/layout' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/components/welcome' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/index' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/reducers' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/routes' {
  declare module.exports: any;
}

declare module 'ninja/examples/client/types' {
  declare module.exports: any;
}

declare module 'ninja/examples/server/index' {
  declare module.exports: any;
}

declare module 'ninja/examples/server/meta' {
  declare module.exports: any;
}

declare module 'ninja/examples/server/style' {
  declare module.exports: any;
}

declare module 'ninja/examples/server/webpack' {
  declare module.exports: any;
}

declare module 'ninja/scripts/build' {
  declare module.exports: any;
}

declare module 'ninja/src/ninja/arc' {
  declare module.exports: any;
}

declare module 'ninja/src/ninja/icons/icon' {
  declare module.exports: any;
}

declare module 'ninja/src/ninja/icons/pause' {
  declare module.exports: any;
}

declare module 'ninja/src/ninja/icons/play' {
  declare module.exports: any;
}

declare module 'ninja/src/ninja/icons/repeat' {
  declare module.exports: any;
}

declare module 'ninja/src/ninja/icons/stop' {
  declare module.exports: any;
}

declare module 'ninja/src/ninja/index' {
  declare module.exports: any;
}

declare module 'ninja/test/icon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ninja/build/arc.js' {
  declare module.exports: $Exports<'ninja/build/arc'>;
}
declare module 'ninja/build/bin.js' {
  declare module.exports: $Exports<'ninja/build/bin'>;
}
declare module 'ninja/build/graphics/pause.js' {
  declare module.exports: $Exports<'ninja/build/graphics/pause'>;
}
declare module 'ninja/build/graphics/play.js' {
  declare module.exports: $Exports<'ninja/build/graphics/play'>;
}
declare module 'ninja/build/graphics/stop.js' {
  declare module.exports: $Exports<'ninja/build/graphics/stop'>;
}
declare module 'ninja/build/icon.js' {
  declare module.exports: $Exports<'ninja/build/icon'>;
}
declare module 'ninja/build/icons/icon.js' {
  declare module.exports: $Exports<'ninja/build/icons/icon'>;
}
declare module 'ninja/build/icons/pause.js' {
  declare module.exports: $Exports<'ninja/build/icons/pause'>;
}
declare module 'ninja/build/icons/play.js' {
  declare module.exports: $Exports<'ninja/build/icons/play'>;
}
declare module 'ninja/build/icons/repeat.js' {
  declare module.exports: $Exports<'ninja/build/icons/repeat'>;
}
declare module 'ninja/build/icons/stop.js' {
  declare module.exports: $Exports<'ninja/build/icons/stop'>;
}
declare module 'ninja/build/index.js' {
  declare module.exports: $Exports<'ninja/build/index'>;
}
declare module 'ninja/examples/client/actions.js' {
  declare module.exports: $Exports<'ninja/examples/client/actions'>;
}
declare module 'ninja/examples/client/components/arc/download.js' {
  declare module.exports: $Exports<'ninja/examples/client/components/arc/download'>;
}
declare module 'ninja/examples/client/components/arc/index.js' {
  declare module.exports: $Exports<'ninja/examples/client/components/arc/index'>;
}
declare module 'ninja/examples/client/components/arc/playback.js' {
  declare module.exports: $Exports<'ninja/examples/client/components/arc/playback'>;
}
declare module 'ninja/examples/client/components/arc/rainbow.js' {
  declare module.exports: $Exports<'ninja/examples/client/components/arc/rainbow'>;
}
declare module 'ninja/examples/client/components/icon.js' {
  declare module.exports: $Exports<'ninja/examples/client/components/icon'>;
}
declare module 'ninja/examples/client/components/layout.js' {
  declare module.exports: $Exports<'ninja/examples/client/components/layout'>;
}
declare module 'ninja/examples/client/components/welcome.js' {
  declare module.exports: $Exports<'ninja/examples/client/components/welcome'>;
}
declare module 'ninja/examples/client/index.js' {
  declare module.exports: $Exports<'ninja/examples/client/index'>;
}
declare module 'ninja/examples/client/reducers.js' {
  declare module.exports: $Exports<'ninja/examples/client/reducers'>;
}
declare module 'ninja/examples/client/routes.js' {
  declare module.exports: $Exports<'ninja/examples/client/routes'>;
}
declare module 'ninja/examples/client/types.js' {
  declare module.exports: $Exports<'ninja/examples/client/types'>;
}
declare module 'ninja/examples/server/index.js' {
  declare module.exports: $Exports<'ninja/examples/server/index'>;
}
declare module 'ninja/examples/server/meta.js' {
  declare module.exports: $Exports<'ninja/examples/server/meta'>;
}
declare module 'ninja/examples/server/style.js' {
  declare module.exports: $Exports<'ninja/examples/server/style'>;
}
declare module 'ninja/examples/server/webpack.js' {
  declare module.exports: $Exports<'ninja/examples/server/webpack'>;
}
declare module 'ninja/scripts/build.js' {
  declare module.exports: $Exports<'ninja/scripts/build'>;
}
declare module 'ninja/src/ninja/arc.js' {
  declare module.exports: $Exports<'ninja/src/ninja/arc'>;
}
declare module 'ninja/src/ninja/icons/icon.js' {
  declare module.exports: $Exports<'ninja/src/ninja/icons/icon'>;
}
declare module 'ninja/src/ninja/icons/pause.js' {
  declare module.exports: $Exports<'ninja/src/ninja/icons/pause'>;
}
declare module 'ninja/src/ninja/icons/play.js' {
  declare module.exports: $Exports<'ninja/src/ninja/icons/play'>;
}
declare module 'ninja/src/ninja/icons/repeat.js' {
  declare module.exports: $Exports<'ninja/src/ninja/icons/repeat'>;
}
declare module 'ninja/src/ninja/icons/stop.js' {
  declare module.exports: $Exports<'ninja/src/ninja/icons/stop'>;
}
declare module 'ninja/src/ninja/index.js' {
  declare module.exports: $Exports<'ninja/src/ninja/index'>;
}
declare module 'ninja/test/icon.js' {
  declare module.exports: $Exports<'ninja/test/icon'>;
}
