// flow-typed signature: 4f7174ef833035730afa2b33c1be040f
// flow-typed version: <<STUB>>/p2_v^0.7.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'p2/build/p2' {
  declare module.exports: any;
}

declare module 'p2/build/p2.min' {
  declare module.exports: any;
}

declare module 'p2/build/p2.renderer' {
  declare module.exports: any;
}

declare module 'p2/build/p2.renderer.min' {
  declare module.exports: any;
}

declare module 'p2/demos/js/dat.gui' {
  declare module.exports: any;
}

declare module 'p2/demos/js/pixi' {
  declare module.exports: any;
}

declare module 'p2/demos/js/Renderer' {
  declare module.exports: any;
}

declare module 'p2/demos/js/WebGLRenderer' {
  declare module.exports: any;
}

declare module 'p2/docs/api' {
  declare module.exports: any;
}

declare module 'p2/docs/assets/js/api-filter' {
  declare module.exports: any;
}

declare module 'p2/docs/assets/js/api-list' {
  declare module.exports: any;
}

declare module 'p2/docs/assets/js/api-search' {
  declare module.exports: any;
}

declare module 'p2/docs/assets/js/apidocs' {
  declare module.exports: any;
}

declare module 'p2/docs/assets/js/yui-prettify' {
  declare module.exports: any;
}

declare module 'p2/docs/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'p2/Gruntfile' {
  declare module.exports: any;
}

declare module 'p2/src/collision/AABB' {
  declare module.exports: any;
}

declare module 'p2/src/collision/Broadphase' {
  declare module.exports: any;
}

declare module 'p2/src/collision/NaiveBroadphase' {
  declare module.exports: any;
}

declare module 'p2/src/collision/Narrowphase' {
  declare module.exports: any;
}

declare module 'p2/src/collision/Ray' {
  declare module.exports: any;
}

declare module 'p2/src/collision/RaycastResult' {
  declare module.exports: any;
}

declare module 'p2/src/collision/SAPBroadphase' {
  declare module.exports: any;
}

declare module 'p2/src/constraints/Constraint' {
  declare module.exports: any;
}

declare module 'p2/src/constraints/DistanceConstraint' {
  declare module.exports: any;
}

declare module 'p2/src/constraints/GearConstraint' {
  declare module.exports: any;
}

declare module 'p2/src/constraints/LockConstraint' {
  declare module.exports: any;
}

declare module 'p2/src/constraints/PrismaticConstraint' {
  declare module.exports: any;
}

declare module 'p2/src/constraints/RevoluteConstraint' {
  declare module.exports: any;
}

declare module 'p2/src/equations/AngleLockEquation' {
  declare module.exports: any;
}

declare module 'p2/src/equations/ContactEquation' {
  declare module.exports: any;
}

declare module 'p2/src/equations/Equation' {
  declare module.exports: any;
}

declare module 'p2/src/equations/FrictionEquation' {
  declare module.exports: any;
}

declare module 'p2/src/equations/RotationalLockEquation' {
  declare module.exports: any;
}

declare module 'p2/src/equations/RotationalVelocityEquation' {
  declare module.exports: any;
}

declare module 'p2/src/events/EventEmitter' {
  declare module.exports: any;
}

declare module 'p2/src/material/ContactMaterial' {
  declare module.exports: any;
}

declare module 'p2/src/material/Material' {
  declare module.exports: any;
}

declare module 'p2/src/math/polyk' {
  declare module.exports: any;
}

declare module 'p2/src/math/vec2' {
  declare module.exports: any;
}

declare module 'p2/src/objects/Body' {
  declare module.exports: any;
}

declare module 'p2/src/objects/LinearSpring' {
  declare module.exports: any;
}

declare module 'p2/src/objects/RotationalSpring' {
  declare module.exports: any;
}

declare module 'p2/src/objects/Spring' {
  declare module.exports: any;
}

declare module 'p2/src/objects/TopDownVehicle' {
  declare module.exports: any;
}

declare module 'p2/src/p2' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Box' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Capsule' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Circle' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Convex' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Heightfield' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Line' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Particle' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Plane' {
  declare module.exports: any;
}

declare module 'p2/src/shapes/Shape' {
  declare module.exports: any;
}

declare module 'p2/src/solver/GSSolver' {
  declare module.exports: any;
}

declare module 'p2/src/solver/Solver' {
  declare module.exports: any;
}

declare module 'p2/src/utils/ContactEquationPool' {
  declare module.exports: any;
}

declare module 'p2/src/utils/FrictionEquationPool' {
  declare module.exports: any;
}

declare module 'p2/src/utils/IslandNodePool' {
  declare module.exports: any;
}

declare module 'p2/src/utils/IslandPool' {
  declare module.exports: any;
}

declare module 'p2/src/utils/OverlapKeeper' {
  declare module.exports: any;
}

declare module 'p2/src/utils/OverlapKeeperRecord' {
  declare module.exports: any;
}

declare module 'p2/src/utils/OverlapKeeperRecordPool' {
  declare module.exports: any;
}

declare module 'p2/src/utils/Pool' {
  declare module.exports: any;
}

declare module 'p2/src/utils/TupleDictionary' {
  declare module.exports: any;
}

declare module 'p2/src/utils/Utils' {
  declare module.exports: any;
}

declare module 'p2/src/world/Island' {
  declare module.exports: any;
}

declare module 'p2/src/world/IslandManager' {
  declare module.exports: any;
}

declare module 'p2/src/world/IslandNode' {
  declare module.exports: any;
}

declare module 'p2/src/world/World' {
  declare module.exports: any;
}

declare module 'p2/test/collision/AABB' {
  declare module.exports: any;
}

declare module 'p2/test/collision/Broadphase' {
  declare module.exports: any;
}

declare module 'p2/test/collision/NaiveBroadphase' {
  declare module.exports: any;
}

declare module 'p2/test/collision/Narrowphase' {
  declare module.exports: any;
}

declare module 'p2/test/collision/Ray' {
  declare module.exports: any;
}

declare module 'p2/test/collision/RaycastResult' {
  declare module.exports: any;
}

declare module 'p2/test/collision/SAPBroadphase' {
  declare module.exports: any;
}

declare module 'p2/test/constraints/Constraint' {
  declare module.exports: any;
}

declare module 'p2/test/constraints/DistanceConstraint' {
  declare module.exports: any;
}

declare module 'p2/test/constraints/GearConstraint' {
  declare module.exports: any;
}

declare module 'p2/test/constraints/LockConstraint' {
  declare module.exports: any;
}

declare module 'p2/test/constraints/PrismaticConstraint' {
  declare module.exports: any;
}

declare module 'p2/test/constraints/RevoluteConstraint' {
  declare module.exports: any;
}

declare module 'p2/test/equations/AngleLockEquation' {
  declare module.exports: any;
}

declare module 'p2/test/equations/ContactEquation' {
  declare module.exports: any;
}

declare module 'p2/test/equations/Equation' {
  declare module.exports: any;
}

declare module 'p2/test/equations/FrictionEquation' {
  declare module.exports: any;
}

declare module 'p2/test/equations/RotationalLockEquation' {
  declare module.exports: any;
}

declare module 'p2/test/equations/RotationalVelocityEquation' {
  declare module.exports: any;
}

declare module 'p2/test/events/EventEmitter' {
  declare module.exports: any;
}

declare module 'p2/test/material/ContactMaterial' {
  declare module.exports: any;
}

declare module 'p2/test/material/Material' {
  declare module.exports: any;
}

declare module 'p2/test/math/vec2' {
  declare module.exports: any;
}

declare module 'p2/test/objects/Body' {
  declare module.exports: any;
}

declare module 'p2/test/objects/LinearSpring' {
  declare module.exports: any;
}

declare module 'p2/test/objects/RotationalSpring' {
  declare module.exports: any;
}

declare module 'p2/test/shapes/Box' {
  declare module.exports: any;
}

declare module 'p2/test/shapes/Capsule' {
  declare module.exports: any;
}

declare module 'p2/test/shapes/Circle' {
  declare module.exports: any;
}

declare module 'p2/test/shapes/Convex' {
  declare module.exports: any;
}

declare module 'p2/test/shapes/Line' {
  declare module.exports: any;
}

declare module 'p2/test/shapes/Particle' {
  declare module.exports: any;
}

declare module 'p2/test/shapes/Plane' {
  declare module.exports: any;
}

declare module 'p2/test/shapes/Shape' {
  declare module.exports: any;
}

declare module 'p2/test/solver/GSSolver' {
  declare module.exports: any;
}

declare module 'p2/test/solver/Solver' {
  declare module.exports: any;
}

declare module 'p2/test/utils/ContactEquationPool' {
  declare module.exports: any;
}

declare module 'p2/test/utils/OverlapKeeper' {
  declare module.exports: any;
}

declare module 'p2/test/utils/TupleDictionary' {
  declare module.exports: any;
}

declare module 'p2/test/utils/Utils' {
  declare module.exports: any;
}

declare module 'p2/test/world/IslandManager' {
  declare module.exports: any;
}

declare module 'p2/test/world/World' {
  declare module.exports: any;
}

// Filename aliases
declare module 'p2/build/p2.js' {
  declare module.exports: $Exports<'p2/build/p2'>;
}
declare module 'p2/build/p2.min.js' {
  declare module.exports: $Exports<'p2/build/p2.min'>;
}
declare module 'p2/build/p2.renderer.js' {
  declare module.exports: $Exports<'p2/build/p2.renderer'>;
}
declare module 'p2/build/p2.renderer.min.js' {
  declare module.exports: $Exports<'p2/build/p2.renderer.min'>;
}
declare module 'p2/demos/js/dat.gui.js' {
  declare module.exports: $Exports<'p2/demos/js/dat.gui'>;
}
declare module 'p2/demos/js/pixi.js' {
  declare module.exports: $Exports<'p2/demos/js/pixi'>;
}
declare module 'p2/demos/js/Renderer.js' {
  declare module.exports: $Exports<'p2/demos/js/Renderer'>;
}
declare module 'p2/demos/js/WebGLRenderer.js' {
  declare module.exports: $Exports<'p2/demos/js/WebGLRenderer'>;
}
declare module 'p2/docs/api.js' {
  declare module.exports: $Exports<'p2/docs/api'>;
}
declare module 'p2/docs/assets/js/api-filter.js' {
  declare module.exports: $Exports<'p2/docs/assets/js/api-filter'>;
}
declare module 'p2/docs/assets/js/api-list.js' {
  declare module.exports: $Exports<'p2/docs/assets/js/api-list'>;
}
declare module 'p2/docs/assets/js/api-search.js' {
  declare module.exports: $Exports<'p2/docs/assets/js/api-search'>;
}
declare module 'p2/docs/assets/js/apidocs.js' {
  declare module.exports: $Exports<'p2/docs/assets/js/apidocs'>;
}
declare module 'p2/docs/assets/js/yui-prettify.js' {
  declare module.exports: $Exports<'p2/docs/assets/js/yui-prettify'>;
}
declare module 'p2/docs/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'p2/docs/assets/vendor/prettify/prettify-min'>;
}
declare module 'p2/Gruntfile.js' {
  declare module.exports: $Exports<'p2/Gruntfile'>;
}
declare module 'p2/src/collision/AABB.js' {
  declare module.exports: $Exports<'p2/src/collision/AABB'>;
}
declare module 'p2/src/collision/Broadphase.js' {
  declare module.exports: $Exports<'p2/src/collision/Broadphase'>;
}
declare module 'p2/src/collision/NaiveBroadphase.js' {
  declare module.exports: $Exports<'p2/src/collision/NaiveBroadphase'>;
}
declare module 'p2/src/collision/Narrowphase.js' {
  declare module.exports: $Exports<'p2/src/collision/Narrowphase'>;
}
declare module 'p2/src/collision/Ray.js' {
  declare module.exports: $Exports<'p2/src/collision/Ray'>;
}
declare module 'p2/src/collision/RaycastResult.js' {
  declare module.exports: $Exports<'p2/src/collision/RaycastResult'>;
}
declare module 'p2/src/collision/SAPBroadphase.js' {
  declare module.exports: $Exports<'p2/src/collision/SAPBroadphase'>;
}
declare module 'p2/src/constraints/Constraint.js' {
  declare module.exports: $Exports<'p2/src/constraints/Constraint'>;
}
declare module 'p2/src/constraints/DistanceConstraint.js' {
  declare module.exports: $Exports<'p2/src/constraints/DistanceConstraint'>;
}
declare module 'p2/src/constraints/GearConstraint.js' {
  declare module.exports: $Exports<'p2/src/constraints/GearConstraint'>;
}
declare module 'p2/src/constraints/LockConstraint.js' {
  declare module.exports: $Exports<'p2/src/constraints/LockConstraint'>;
}
declare module 'p2/src/constraints/PrismaticConstraint.js' {
  declare module.exports: $Exports<'p2/src/constraints/PrismaticConstraint'>;
}
declare module 'p2/src/constraints/RevoluteConstraint.js' {
  declare module.exports: $Exports<'p2/src/constraints/RevoluteConstraint'>;
}
declare module 'p2/src/equations/AngleLockEquation.js' {
  declare module.exports: $Exports<'p2/src/equations/AngleLockEquation'>;
}
declare module 'p2/src/equations/ContactEquation.js' {
  declare module.exports: $Exports<'p2/src/equations/ContactEquation'>;
}
declare module 'p2/src/equations/Equation.js' {
  declare module.exports: $Exports<'p2/src/equations/Equation'>;
}
declare module 'p2/src/equations/FrictionEquation.js' {
  declare module.exports: $Exports<'p2/src/equations/FrictionEquation'>;
}
declare module 'p2/src/equations/RotationalLockEquation.js' {
  declare module.exports: $Exports<'p2/src/equations/RotationalLockEquation'>;
}
declare module 'p2/src/equations/RotationalVelocityEquation.js' {
  declare module.exports: $Exports<'p2/src/equations/RotationalVelocityEquation'>;
}
declare module 'p2/src/events/EventEmitter.js' {
  declare module.exports: $Exports<'p2/src/events/EventEmitter'>;
}
declare module 'p2/src/material/ContactMaterial.js' {
  declare module.exports: $Exports<'p2/src/material/ContactMaterial'>;
}
declare module 'p2/src/material/Material.js' {
  declare module.exports: $Exports<'p2/src/material/Material'>;
}
declare module 'p2/src/math/polyk.js' {
  declare module.exports: $Exports<'p2/src/math/polyk'>;
}
declare module 'p2/src/math/vec2.js' {
  declare module.exports: $Exports<'p2/src/math/vec2'>;
}
declare module 'p2/src/objects/Body.js' {
  declare module.exports: $Exports<'p2/src/objects/Body'>;
}
declare module 'p2/src/objects/LinearSpring.js' {
  declare module.exports: $Exports<'p2/src/objects/LinearSpring'>;
}
declare module 'p2/src/objects/RotationalSpring.js' {
  declare module.exports: $Exports<'p2/src/objects/RotationalSpring'>;
}
declare module 'p2/src/objects/Spring.js' {
  declare module.exports: $Exports<'p2/src/objects/Spring'>;
}
declare module 'p2/src/objects/TopDownVehicle.js' {
  declare module.exports: $Exports<'p2/src/objects/TopDownVehicle'>;
}
declare module 'p2/src/p2.js' {
  declare module.exports: $Exports<'p2/src/p2'>;
}
declare module 'p2/src/shapes/Box.js' {
  declare module.exports: $Exports<'p2/src/shapes/Box'>;
}
declare module 'p2/src/shapes/Capsule.js' {
  declare module.exports: $Exports<'p2/src/shapes/Capsule'>;
}
declare module 'p2/src/shapes/Circle.js' {
  declare module.exports: $Exports<'p2/src/shapes/Circle'>;
}
declare module 'p2/src/shapes/Convex.js' {
  declare module.exports: $Exports<'p2/src/shapes/Convex'>;
}
declare module 'p2/src/shapes/Heightfield.js' {
  declare module.exports: $Exports<'p2/src/shapes/Heightfield'>;
}
declare module 'p2/src/shapes/Line.js' {
  declare module.exports: $Exports<'p2/src/shapes/Line'>;
}
declare module 'p2/src/shapes/Particle.js' {
  declare module.exports: $Exports<'p2/src/shapes/Particle'>;
}
declare module 'p2/src/shapes/Plane.js' {
  declare module.exports: $Exports<'p2/src/shapes/Plane'>;
}
declare module 'p2/src/shapes/Shape.js' {
  declare module.exports: $Exports<'p2/src/shapes/Shape'>;
}
declare module 'p2/src/solver/GSSolver.js' {
  declare module.exports: $Exports<'p2/src/solver/GSSolver'>;
}
declare module 'p2/src/solver/Solver.js' {
  declare module.exports: $Exports<'p2/src/solver/Solver'>;
}
declare module 'p2/src/utils/ContactEquationPool.js' {
  declare module.exports: $Exports<'p2/src/utils/ContactEquationPool'>;
}
declare module 'p2/src/utils/FrictionEquationPool.js' {
  declare module.exports: $Exports<'p2/src/utils/FrictionEquationPool'>;
}
declare module 'p2/src/utils/IslandNodePool.js' {
  declare module.exports: $Exports<'p2/src/utils/IslandNodePool'>;
}
declare module 'p2/src/utils/IslandPool.js' {
  declare module.exports: $Exports<'p2/src/utils/IslandPool'>;
}
declare module 'p2/src/utils/OverlapKeeper.js' {
  declare module.exports: $Exports<'p2/src/utils/OverlapKeeper'>;
}
declare module 'p2/src/utils/OverlapKeeperRecord.js' {
  declare module.exports: $Exports<'p2/src/utils/OverlapKeeperRecord'>;
}
declare module 'p2/src/utils/OverlapKeeperRecordPool.js' {
  declare module.exports: $Exports<'p2/src/utils/OverlapKeeperRecordPool'>;
}
declare module 'p2/src/utils/Pool.js' {
  declare module.exports: $Exports<'p2/src/utils/Pool'>;
}
declare module 'p2/src/utils/TupleDictionary.js' {
  declare module.exports: $Exports<'p2/src/utils/TupleDictionary'>;
}
declare module 'p2/src/utils/Utils.js' {
  declare module.exports: $Exports<'p2/src/utils/Utils'>;
}
declare module 'p2/src/world/Island.js' {
  declare module.exports: $Exports<'p2/src/world/Island'>;
}
declare module 'p2/src/world/IslandManager.js' {
  declare module.exports: $Exports<'p2/src/world/IslandManager'>;
}
declare module 'p2/src/world/IslandNode.js' {
  declare module.exports: $Exports<'p2/src/world/IslandNode'>;
}
declare module 'p2/src/world/World.js' {
  declare module.exports: $Exports<'p2/src/world/World'>;
}
declare module 'p2/test/collision/AABB.js' {
  declare module.exports: $Exports<'p2/test/collision/AABB'>;
}
declare module 'p2/test/collision/Broadphase.js' {
  declare module.exports: $Exports<'p2/test/collision/Broadphase'>;
}
declare module 'p2/test/collision/NaiveBroadphase.js' {
  declare module.exports: $Exports<'p2/test/collision/NaiveBroadphase'>;
}
declare module 'p2/test/collision/Narrowphase.js' {
  declare module.exports: $Exports<'p2/test/collision/Narrowphase'>;
}
declare module 'p2/test/collision/Ray.js' {
  declare module.exports: $Exports<'p2/test/collision/Ray'>;
}
declare module 'p2/test/collision/RaycastResult.js' {
  declare module.exports: $Exports<'p2/test/collision/RaycastResult'>;
}
declare module 'p2/test/collision/SAPBroadphase.js' {
  declare module.exports: $Exports<'p2/test/collision/SAPBroadphase'>;
}
declare module 'p2/test/constraints/Constraint.js' {
  declare module.exports: $Exports<'p2/test/constraints/Constraint'>;
}
declare module 'p2/test/constraints/DistanceConstraint.js' {
  declare module.exports: $Exports<'p2/test/constraints/DistanceConstraint'>;
}
declare module 'p2/test/constraints/GearConstraint.js' {
  declare module.exports: $Exports<'p2/test/constraints/GearConstraint'>;
}
declare module 'p2/test/constraints/LockConstraint.js' {
  declare module.exports: $Exports<'p2/test/constraints/LockConstraint'>;
}
declare module 'p2/test/constraints/PrismaticConstraint.js' {
  declare module.exports: $Exports<'p2/test/constraints/PrismaticConstraint'>;
}
declare module 'p2/test/constraints/RevoluteConstraint.js' {
  declare module.exports: $Exports<'p2/test/constraints/RevoluteConstraint'>;
}
declare module 'p2/test/equations/AngleLockEquation.js' {
  declare module.exports: $Exports<'p2/test/equations/AngleLockEquation'>;
}
declare module 'p2/test/equations/ContactEquation.js' {
  declare module.exports: $Exports<'p2/test/equations/ContactEquation'>;
}
declare module 'p2/test/equations/Equation.js' {
  declare module.exports: $Exports<'p2/test/equations/Equation'>;
}
declare module 'p2/test/equations/FrictionEquation.js' {
  declare module.exports: $Exports<'p2/test/equations/FrictionEquation'>;
}
declare module 'p2/test/equations/RotationalLockEquation.js' {
  declare module.exports: $Exports<'p2/test/equations/RotationalLockEquation'>;
}
declare module 'p2/test/equations/RotationalVelocityEquation.js' {
  declare module.exports: $Exports<'p2/test/equations/RotationalVelocityEquation'>;
}
declare module 'p2/test/events/EventEmitter.js' {
  declare module.exports: $Exports<'p2/test/events/EventEmitter'>;
}
declare module 'p2/test/material/ContactMaterial.js' {
  declare module.exports: $Exports<'p2/test/material/ContactMaterial'>;
}
declare module 'p2/test/material/Material.js' {
  declare module.exports: $Exports<'p2/test/material/Material'>;
}
declare module 'p2/test/math/vec2.js' {
  declare module.exports: $Exports<'p2/test/math/vec2'>;
}
declare module 'p2/test/objects/Body.js' {
  declare module.exports: $Exports<'p2/test/objects/Body'>;
}
declare module 'p2/test/objects/LinearSpring.js' {
  declare module.exports: $Exports<'p2/test/objects/LinearSpring'>;
}
declare module 'p2/test/objects/RotationalSpring.js' {
  declare module.exports: $Exports<'p2/test/objects/RotationalSpring'>;
}
declare module 'p2/test/shapes/Box.js' {
  declare module.exports: $Exports<'p2/test/shapes/Box'>;
}
declare module 'p2/test/shapes/Capsule.js' {
  declare module.exports: $Exports<'p2/test/shapes/Capsule'>;
}
declare module 'p2/test/shapes/Circle.js' {
  declare module.exports: $Exports<'p2/test/shapes/Circle'>;
}
declare module 'p2/test/shapes/Convex.js' {
  declare module.exports: $Exports<'p2/test/shapes/Convex'>;
}
declare module 'p2/test/shapes/Line.js' {
  declare module.exports: $Exports<'p2/test/shapes/Line'>;
}
declare module 'p2/test/shapes/Particle.js' {
  declare module.exports: $Exports<'p2/test/shapes/Particle'>;
}
declare module 'p2/test/shapes/Plane.js' {
  declare module.exports: $Exports<'p2/test/shapes/Plane'>;
}
declare module 'p2/test/shapes/Shape.js' {
  declare module.exports: $Exports<'p2/test/shapes/Shape'>;
}
declare module 'p2/test/solver/GSSolver.js' {
  declare module.exports: $Exports<'p2/test/solver/GSSolver'>;
}
declare module 'p2/test/solver/Solver.js' {
  declare module.exports: $Exports<'p2/test/solver/Solver'>;
}
declare module 'p2/test/utils/ContactEquationPool.js' {
  declare module.exports: $Exports<'p2/test/utils/ContactEquationPool'>;
}
declare module 'p2/test/utils/OverlapKeeper.js' {
  declare module.exports: $Exports<'p2/test/utils/OverlapKeeper'>;
}
declare module 'p2/test/utils/TupleDictionary.js' {
  declare module.exports: $Exports<'p2/test/utils/TupleDictionary'>;
}
declare module 'p2/test/utils/Utils.js' {
  declare module.exports: $Exports<'p2/test/utils/Utils'>;
}
declare module 'p2/test/world/IslandManager.js' {
  declare module.exports: $Exports<'p2/test/world/IslandManager'>;
}
declare module 'p2/test/world/World.js' {
  declare module.exports: $Exports<'p2/test/world/World'>;
}
